version: "2"
services:
  pgbouncer:
    build:
      context: fabric8-analytics-pgbouncer/
      dockerfile: Dockerfile
  postgres:
    build:
      context: postgres-docker/
      dockerfile: Dockerfile
  server:
    build:
      context: fabric8-analytics-server/
      dockerfile: Dockerfile
    volumes:
     - ./fabric8-analytics-worker/f8a_worker:/usr/local/lib/python3.6/site-packages/f8a_worker:ro,z
     - ./fabric8-analytics-server/bayesian:/usr/local/lib/python3.6/site-packages/bayesian:ro,z
     - ./fabric8-analytics-server/coreapi-httpd.conf:/etc/httpd/conf.d/coreapi-httpd.conf:ro,z
  jobs:
    build:
      context: fabric8-analytics-jobs/
      dockerfile: Dockerfile
    volumes:
     - ./fabric8-analytics-worker/f8a_worker:/usr/local/lib/python3.6/site-packages/f8a_worker:ro,z
     - ./fabric8-analytics-jobs/f8a_jobs:/usr/local/lib/python3.6/site-packages/f8a_jobs:ro,z
     - ./fabric8-analytics-jobs/f8a-jobs.py:/usr/bin/f8a-jobs.py:ro,z
  worker-api: &worker
    build:
      context: fabric8-analytics-worker/
      dockerfile: Dockerfile
    volumes:
     - ./fabric8-analytics-worker/f8a_worker:/usr/local/lib/python3.6/site-packages/f8a_worker:ro,z
     - ./fabric8-analytics-worker/hack/workers.sh:/usr/bin/workers.sh:ro,z
  worker-ingestion:
    <<: *worker
  worker-priority:
    <<: *worker
  worker-db-migrations:
    build:
      context: fabric8-analytics-worker/
      dockerfile: Dockerfile
    volumes:
     - ./fabric8-analytics-worker/alembic:/alembic/alembic:ro,z
  data-model-importer:
    build:
      context: fabric8-analytics-data-model/
      dockerfile: Dockerfile.data-model
    volumes:
       - ./fabric8-analytics-data-model/src:/src:ro,z
  minio-s3:
    # Uncomment this if you want to have S3 data persistent
    #volumes:
    # - ./hack/s3:/export:rw,z
    # - ./hack/s3:/root/.mini:rw,z
