apiVersion: v1
kind: Template
metadata:
  name: bayesian-config
objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: bayesian-config
  data:
    deployment-prefix: "${DEPLOYMENT_PREFIX}"
    s3-bucket-for-analyses: "${DEPLOYMENT_PREFIX}-${S3_BUCKET_FOR_ANALYSES}"
    s3-bucket-for-package-analyses: "${DEPLOYMENT_PREFIX}-${S3_BUCKET_FOR_PACKAGE_ANALYSES}"
    aws-default-region: "${AWS_DEFAULT_REGION}"
    dynamodb-prefix: "${DEPLOYMENT_PREFIX}"
    keycloak-url: "${KEYCLOAK_URL}"
    three-scale-api-host-url: "${THREE_SCALE_API_HOST_URL}"
    auth-url: "${AUTH_URL}"
    notification-url: "${NOTIFICATION_URL}"

parameters:
- description: Deployment prefix used for deployment-specific AWS resources
  displayName: Deployment prefix
  required: true
  name: DEPLOYMENT_PREFIX
  value: "dev"

- description: Name of the S3 bucket where to store analyses
  displayName: S3 bucket for analyses
  required: true
  name: S3_BUCKET_FOR_ANALYSES
  value: "bayesian-core-data"

- description: Name of the S3 bucket where to store package analyses
  displayName: S3 bucket for package analyses
  required: true
  name: S3_BUCKET_FOR_PACKAGE_ANALYSES
  value: "bayesian-core-package-data"

- description: AWS default region to use
  displayName: AWS default region
  required: true
  name: AWS_DEFAULT_REGION
  value: "us-east-1"

- description: Keycloak URL
  displayName: Keycloak URL
  required: false
  name: KEYCLOAK_URL
  value: ""

- description: 3scale API host URL
  displayName: 3scale API host URL
  required: false
  name: THREE_SCALE_API_HOST_URL
  value: ""

- description: Auth URL
  displayName: Auth URL
  required: true
  name: AUTH_URL
  value: "https://auth.prod-preview.openshift.io"

- description: Notification URL
  displayName: Notification URL
  required: false
  name: NOTIFICATION_URL
  value: ""

