apiVersion: apps/v1
kind: Deployment
metadata:
  name: f8a-postgres
  labels:
    f8a-component: f8a-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      f8a-component: f8a-postgres
  template:
    metadata:
      labels:
        f8a-component: f8a-postgres
    spec:
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: f8a-postgres
      containers:
        - name: postgres
          image: postgres:9.6
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: coreapi-postgres
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  key: database
                  name: coreapi-postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: coreapi-postgres
            - name: PGDATA
              value: "/var/lib/postgres/data/f8a"
          volumeMounts:
            - name: postgres-data
              mountPath: "/var/lib/postgres/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: f8a-postgres
  labels:
    f8a-component: f8a-postgres
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "10Gi"
    volumeName: "f8a-postgres"
---
apiVersion: v1
kind: Service
metadata:
  name: f8a-postgres
  labels:
    f8a-component: f8a-postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      protocol: TCP
      name: postgres
      targetPort: 5432
  selector:
    f8a-component: f8a-postgres
